### ISSUE TITLE
Notas de Credito

### ISSUE THREAD

**Issue by jlesmepy** [roshkadev/rshk-jsifenlib#17]
Buenas, me podrían ayuda por favor para entender el envío de una NC al Sifen utilizando la libreria.

// Grupo E
TgDtipDE gDtipDE = new TgDtipDE();

//Nota de Credito
TgCamNCDE gNCDE = new TgCamNCDE();
if (pTipoFactura.equals("NOTA_DE_CREDITO_ELECTRONICA")) {
    gNCDE.setiMotEmi(TiMotEmi.DEVOLUCION_Y_AJUSTES_DE_PRECIOS);
    gDtipDE.setgCamNCDE(gNCDE);
}

ERROR:

Exception in thread "main" java.lang.NullPointerException
        at com.roshka.sifen.core.beans.DocumentoElectronico.setupDE(DocumentoElectronico.java:284)
        at com.roshka.sifen.core.beans.DocumentoElectronico.setupSOAPElements(DocumentoElectronico.java:226)
        at com.roshka.sifen.internal.request.ReqRecDe.setupSoapMessage(ReqRecDe.java:33)
        at com.roshka.sifen.internal.request.BaseRequest.makeRequest(BaseRequest.java:32)
        at com.roshka.sifen.internal.request.ReqRecDe.makeRequest(ReqRecDe.java:22)
        at com.roshka.sifen.Sifen.recepcionDE(Sifen.java:184)
        at com.roshka.sifen.Sifen.recepcionDE(Sifen.java:162)

**Comment by martinzarza** [comment]
Podrías dar un poco más de detalle sobre el error que estás teniendo?

**Comment by jlesmepy** [comment]
Y la verdad que es toda la cadena de error que me arroja:

Cuando es un NC solo le estoy asignado datos en este punto mencionado en el msje anterior.

Pero el cuerpo completo sería:

Defino el DE
// Grupo A
DocumentoElectronico DE = new DocumentoElectronico();

//defino la NC

Y luego al final asigno todo al DE

// Grupo E
DE.setgTotSub(new TgTotSub());

Y llamo al obtener:
pcdc = DE.obtenerCDC();

Me retorna esto:

CDC del Documento Electronico -> 05800169697001001000024322022112819965944064
nov 28, 2022 11:33:45 AM com.roshka.sifen.Sifen recepcionDE
INFORMACIÓN: Preparando petición 'Recepción de DE'
Exception in thread "main" java.lang.NullPointerException
        at com.roshka.sifen.core.beans.DocumentoElectronico.setupDE(DocumentoElectronico.java:284)
        at com.roshka.sifen.core.beans.DocumentoElectronico.setupSOAPElements(DocumentoElectronico.java:226)
        at com.roshka.sifen.internal.request.ReqRecDe.setupSoapMessage(ReqRecDe.java:33)
        at com.roshka.sifen.internal.request.BaseRequest.makeRequest(BaseRequest.java:32)
        at com.roshka.sifen.internal.request.ReqRecDe.makeRequest(ReqRecDe.java:22)
        at com.roshka.sifen.Sifen.recepcionDE(Sifen.java:184)
        at com.roshka.sifen.Sifen.recepcionDE(Sifen.java:162)
        at com.sifen_cefisa.Sifen_Cefisa.envioDE(Sifen_Cefisa.java:467)
        at com.sifen_cefisa.Sifen_Cefisa.main(Sifen_Cefisa.java:1148)

**Comment by jlesmepy** [comment]
Creo que va por otro lado el problema que tengo.
En asignar los datos del documento asociado cuando es un NC.
Gracias por la ayuda.
